config/routes.rb
Rails.application.routes.draw do

   root 'films#index'

  resources :films
  resources :actors
  resources :directors
  resources :roles
  resources :productions

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  validates :fname, presence: true
  validates :lname, presence: true

  has_many :roles
  has_many :films, :through => :roles

  def full_name
    [fname, lname].join(' ')
  end

  def full_name=(name)
    split = name.split(' ', 2)
    self.fname = split.first
    self.lname = split.last
  end

  def to_s
    "#{fname} #{lname}"
  end
end

app/models/director.rb
class Director < ActiveRecord::Base

  validates :fname, presence: true
  validates :lname, presence: true

  has_many :productions
  has_many :films, :through => :productions

  def to_s
    "#{fname} #{lname}"
  end
end

app/models/film.rb
class Film < ActiveRecord::Base
  
  validates :title, presence: true
  validates :description, presence: true
  validates :genre, presence: true
  validates :release_date, presence: true

  has_many :roles
  has_many :actors, :through => :roles
  has_many :productions
  has_many :directors, :through => :productions

  def to_s
    "#{title} (#{release_date})"
  end
end

app/models/production.rb
class Production < ActiveRecord::Base

  belongs_to :director
  belongs_to :film
end

app/models/role.rb
class Role < ActiveRecord::Base

  validates :character, presence: true

  belongs_to :actor
  belongs_to :film
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

    def index
        @actors = Actor.all
        respond_to do |format|
            format.html
            format.xml { render xml: @actors }
        end
    end

    def new
        @actor = Actor.new
    end

    def show
        @actor = Actor.find(params[:id])
        respond_to do |format|
            format.html 
            format.xml { render xml: @actor }
            format.json { render json: @actor }
        end
    end

    def create
        @actor = Actor.new(params[:actor].permit(:fname, :lname))
        respond_to do |format|
            if @actor.save
                format.html { redirect_to @actor, notice: 'Actor Added' }
                format.js
            else
                format.html { render :new }
                format.js
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

    def index
        @films = Film.all
    end

    def create
        @film = Film.new(params[:film].permit(:title, :description,
                         :genre, :release_date))
        respond_to do |format|
            if @film.save
                format.html { redirect_to @film, notice: 'Film Added' }
            end
        end
    end

    def new
        @film = Film.new
    end

    def show
        @film = Film.find(params[:id])
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

        def nav_items
        [
            {
             displaytext: 'Films',
             controllername: 'films',
             linkurl: films_path
            },
            {
             displaytext: 'Actors',
             controllername: 'actors',
             linkurl: actors_path
            }
        ]
    end

    def display_nav_item(displaytext, controllername, linkurl)
        raw("<li#{controller_name == controllername ? ' class="active"' : ''}>#{link_to displaytext, linkurl}</li>")
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/actors/_actor.html.erb
<tr>
    <td><%= link_to actor, actor %></td>
</tr>

app/views/actors/_form.html.erb
<% doajax = false unless (defined? doajax) %>
<%= form_for(@actor, remote: doajax) do |f| %>
    <% if @actor.errors.any? %>
        <div id="errors">
            <p>Please correct the following <%= pluralize(@actor.errors.count, "error") %>:</p>
            <ul>
                <% @actor.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= f.label :Name %>
        <%= f.text_field :fname %>
    </div>
    <div>
        <%= f.label :Surname %>
        <%= f.text_field :lname %>
    </div>    
    <div>
        <%= f.submit %>
        <span id="actor"></span>
    </div>
<% end %>

app/views/actors/_sidebar.html.erb
<ul>
    <li><%= link_to 'All Actors', actors_path %></li>
    <li><%= link_to 'New Actors', new_actor_path %></li>
</ul>

app/views/actors/create.js.erb
$(document).ready(function(){
    var actor = "<%= @actor %>"
    $("#actor").html(actor);
});

app/views/actors/index.html.erb
<h1>Actors</h1>

<p>Here are all of the actors:</p>

<table>
    <tbody>
        <tr>
            <th>Actor</th>
        </tr>
        <%= render partial: "actor", collection: @actors %>
    </tbody>
</table>

<% content_for :aside do %>
    <%= render 'sidebar' %>
<% end %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render partial: 'form', locals: { doajax: false } %>

<% content_for :aside do %>
    <%= render 'sidebar' %>
<% end %>

app/views/actors/show.html.erb
<p>Actor: <%= @actor.fname %> <%= @actor.lname %></p>

app/views/films/_film.html.erb
<tr>
    <td><%= link_to film, film %></td>
</tr>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
    <% if @film.errors.any? %>
        <div id="errors">
            <p>Please correct the following <%= pluralize(@film.errors.count, "error") %>:</p>
            <ul>
                <% @film.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description, :size => "23x10" %>
    </div>    
    <div>
        <%= f.label :genre %>
        <%= f.text_field :genre %>
    </div>
        <div>
        <%= f.label :release_date %>
        <%= f.text_field :release_date %>
    </div>
    <div>
        <%= f.submit @film.new_record? ? "Create Film" : "Update Film"  %>
    </div>
<% end %>

app/views/films/_show.html.erb
<p>Film: <%= @film.fname %> <%= @film.lname %></p>

app/views/films/_sidebar.html.erb
<ul>
    <li><%= link_to 'All Films', films_path %></li>
    <li><%= link_to 'New Films', new_film_path %></li>
</ul>

app/views/films/index.html.erb
<h1>Films</h1>

<p>Here are all of the Films:</p>

<table>
    <tbody>
        <tr>
            <th>Film</th>
        </tr>
        <%= render partial: "film", collection: @films %>
    </tbody>
</table>

<% content_for :aside do %>
    <%= render 'sidebar' %>
<% end %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form' %>

<% content_for :aside do %>
    <%= render 'sidebar' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filmdb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "jquery-1.11.2.min", "jquery-ui-1.11.2/jquery-ui.min.js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
        <header>
            <%= link_to content_tag('canvas', 'FilmDatabase', id: 'logocanvas'), root_url %>
            <nav>
                <ul>
                    <% nav_items.each do |nav_item| %>
                        <%= display_nav_item(nav_item[:displaytext], nav_item[:controllername], nav_item[:linkurl]) %>
                    <% end %>
                </ul>
            </nav>
        </header>
        <section id="main">
            <article>
                <%= yield %>
            </article>
            <aside>
                <%= yield :aside %>
            </aside>
        </section>
        <footer>
          <p>Film Database is a <em>Darknawg63 Sample</em> App</p>
        </footer>
    </div>
</body>
</html>